# Generated by Django 4.2.15 on 2024-09-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
