# Generated by Django 4.2.15 on 2024-09-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_rename_ingredients_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='food',
            new_name='name',
        ),
    ]
